'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PortForwarding.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 AccessCheck 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Btn_Access_Text() As String
            Get
                Return ResourceManager.GetString("Btn_Access_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Clear 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Btn_Clear_Text() As String
            Get
                Return ResourceManager.GetString("Btn_Clear_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 DefenseCheck 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Btn_Defense_Text() As String
            Get
                Return ResourceManager.GetString("Btn_Defense_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Export 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Btn_Export_Text() As String
            Get
                Return ResourceManager.GetString("Btn_Export_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Import 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Btn_Import_Text() As String
            Get
                Return ResourceManager.GetString("Btn_Import_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Manager 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Btn_Manager_Text() As String
            Get
                Return ResourceManager.GetString("Btn_Manager_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 ReLoad 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Btn_ReLoad_Text() As String
            Get
                Return ResourceManager.GetString("Btn_ReLoad_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Remove 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Btn_Remove_Text() As String
            Get
                Return ResourceManager.GetString("Btn_Remove_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 ReSet 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Btn_ReSet_Text() As String
            Get
                Return ResourceManager.GetString("Btn_ReSet_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 RmCountlt 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Btn_RmCountlt_Text() As String
            Get
                Return ResourceManager.GetString("Btn_RmCountlt_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 RmHourAgo 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Btn_RmHourAgo_Text() As String
            Get
                Return ResourceManager.GetString("Btn_RmHourAgo_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Start 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Btn_Start_Text_Start() As String
            Get
                Return ResourceManager.GetString("Btn_Start_Text_Start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Stop 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Btn_Start_Text_Stop() As String
            Get
                Return ResourceManager.GetString("Btn_Start_Text_Stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LogAccept 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Chk_LogAccept_Text() As String
            Get
                Return ResourceManager.GetString("Chk_LogAccept_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LogClose 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Chk_LogClose_Text() As String
            Get
                Return ResourceManager.GetString("Chk_LogClose_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LogRevSize 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Chk_LogRevSize_Text() As String
            Get
                Return ResourceManager.GetString("Chk_LogRevSize_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LogSendSize 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Chk_LogSndSize_Text() As String
            Get
                Return ResourceManager.GetString("Chk_LogSndSize_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Count 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CMH_Count_Text() As String
            Get
                Return ResourceManager.GetString("CMH_Count_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 DefenseTime 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CMH_DefenseTime_Text() As String
            Get
                Return ResourceManager.GetString("CMH_DefenseTime_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 IP 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CMH_IP_Text() As String
            Get
                Return ResourceManager.GetString("CMH_IP_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 IsDefensed 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CMH_IsDefensed_Text() As String
            Get
                Return ResourceManager.GetString("CMH_IsDefensed_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LastTime 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CMH_LastTime_Text() As String
            Get
                Return ResourceManager.GetString("CMH_LastTime_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 RevCount 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CMH_RevCount_Text() As String
            Get
                Return ResourceManager.GetString("CMH_RevCount_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Serial 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CMH_Serial_Text() As String
            Get
                Return ResourceManager.GetString("CMH_Serial_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 SndCount 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CMH_SndCount_Text() As String
            Get
                Return ResourceManager.GetString("CMH_SndCount_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Port Firewall 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Frm_Main_Text() As String
            Get
                Return ResourceManager.GetString("Frm_Main_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Manager Client 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GPB_ManagerClient_Text() As String
            Get
                Return ResourceManager.GetString("GPB_ManagerClient_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property IsFalse() As String
            Get
                Return ResourceManager.GetString("IsFalse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Yes 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property IsTrue() As String
            Get
                Return ResourceManager.GetString("IsTrue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Dst： 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Lab_Dst_Text() As String
            Get
                Return ResourceManager.GetString("Lab_Dst_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 RevBufSize： 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Lab_RevBufSize_Text() As String
            Get
                Return ResourceManager.GetString("Lab_RevBufSize_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 SndBufSize： 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Lab_SndBufSize_Text() As String
            Get
                Return ResourceManager.GetString("Lab_SndBufSize_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Src： 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property Lab_Src_Text() As String
            Get
                Return ResourceManager.GetString("Lab_Src_Text", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
